env:
  PICARD_TEST_INPUTS: gs://hellbender/test/resources/
  PICARD_TEST_LOGS: /hellbender-test-logs/build_reports/
  PICARD_TEST_PROJECT: broad-dsde-dev
  PICARD_TEST_STAGING: gs://hellbender-test-logs/staging/
jobs:
  check-secrets:
    name: check if the environment has privileges
    outputs:
      google-credentials: ${{ steps.google-credentials.outputs.defined }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      env:
        GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
      id: google-credentials
      if: ${{ env.GCP_CREDENTIALS != '' }}
      run: echo defined=true >> $GITHUB_OUTPUT
  test:
    continue-on-error: ${{ matrix.experimental }}
    name: Java ${{ matrix.Java }}, Barclay=${{ matrix.run_barclay_tests}} cloud tests
    needs: check-secrets
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - continue-on-error: true
      name: Set up java ${{ matrix.Java }}
      uses: actions/setup-java@v3
      with:
        cache: gradle
        distribution: temurin
        java-version: ${{ matrix.Java }}
    - continue-on-error: true
      name: Compile with Gradle
      run: "./gradlew compileJava \n./gradlew installDist\n"
    - continue-on-error: true
      id: gcloud-auth
      if: needs.check-secrets.outputs.google-credentials == 'true'
      uses: google-github-actions/auth@v0
      with:
        create_credentials_file: true
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}
        project_id: ${{ env.PICARD_TEST_PROJECT }}
    - continue-on-error: true
      if: needs.check-secrets.outputs.google-credentials == 'true'
      name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
    - continue-on-error: true
      if: needs.check-secrets.outputs.google-credentials == 'true'
      name: compile test code
      run: ./gradlew compileTestJava
    - continue-on-error: true
      env:
        TEST_TYPE: cloud
      if: needs.check-secrets.outputs.google-credentials == 'true'
      name: Run tests
      run: "if [[ ${{matrix.run_barclay_tests}} == true ]]; then\n  echo \"Running\
        \ tests using the Barclay command line parser.\"\n  ./gradlew barclayTest\n\
        else\n  echo \"Running tests using the legacy Picard command line parser.\"\
        \n  ./gradlew jacocoTestReport\nfi\n"
    - continue-on-error: true
      if: always()
      name: Upload test results
      uses: actions/upload-artifact@v3
      with:
        name: cloud-test-results-${{ matrix.Java }}-barclay-${{ matrix.run_barclay_tests}}
        path: build/reports/tests
    strategy:
      fail-fast: false
      matrix:
        experimental:
        - false
        java:
        - 17
        run_barclay_tests:
        - true
        - false
name: Cloud Tests
on:
  repository_dispatch:
    types: trigger-ga___cloud_tests.yml
