jobs:
  test:
    continue-on-error: ${{ matrix.experimental }}
    name: Java ${{ matrix.Java }}, Barclay=${{ matrix.run_barclay_tests}} tests
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up java ${{ matrix.Java }}
      uses: actions/setup-java@v3
      with:
        cache: gradle
        distribution: temurin
        java-version: ${{ matrix.Java }}
    - continue-on-error: true
      name: set up R
      run: 'wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo
        apt-key add -

        sudo apt-get -qq update

        sudo apt-get install -y --no-install-recommends r-base-dev r-recommended qpdf

        '
    - continue-on-error: true
      name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - continue-on-error: true
      name: Compile with Gradle
      run: ./gradlew compileJava
    - continue-on-error: true
      name: Run tests
      run: "if [[ ${{matrix.run_barclay_tests}} == true ]]; then\n  echo \"Running\
        \ tests using the Barclay command line parser.\"\n  ./gradlew barclayTest\n\
        else\n  echo \"Running tests using the legacy Picard command line parser.\"\
        \n  ./gradlew jacocoTestReport\nfi\n"
    - continue-on-error: true
      name: Build the jar and run a commandline test for sanity checking
      run: './gradlew currentJar

        java -jar build/libs/picard.jar MarkDuplicates -I testdata/picard/sam/aligned_queryname_sorted.bam
        -O out.bam --METRICS_FILE out.metrics

        '
    - continue-on-error: true
      if: always()
      name: Upload test results
      uses: actions/upload-artifact@v3
      with:
        name: test-results-${{ matrix.Java }}-barclay-${{ matrix.run_barclay_tests}}
        path: build/reports/tests
    strategy:
      fail-fast: false
      matrix:
        experimental:
        - false
        java:
        - 17
        run_barclay_tests:
        - true
        - false
name: Build and Test
on:
  repository_dispatch:
    types: trigger-ga___tests.yml
