jobs:
  appsec-trivy:
    name: DSP AppSec Trivy check
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      uses: broadinstitute/dsp-appsec-trivy-action@v1
name: dsp-appsec-trivy
on:
  repository_dispatch:
    types: trigger-ga___trivy.yml
